### ISSUE TITLE
After uninstall, I still can see a failed service "mailman3-web"

### ISSUE THREAD

**Issue by zero1Dre** [decentral1se/mailman3_ynh#32]
### Describe the bug

After uninstall, I still can see a failed service "mailman3-web"

### Context

- Hardware: VPS bought online
- YunoHost version: 11.0.9.9 (stable)
- I have access to my server: Through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- fresh install
- saw that I can't even log in with admin user and noticed an issue already open for that
- uninstalled
- noticed that service still exists
- emptied browser cache + rebooted VPS
- failed service is still there   

### Expected behavior

Fully and cleanly uninstall the app

### Logs

no logs available

**Comment by tutle** [comment]
maybe try this `sudo apt autoremove mailman3-full python3-mailman-hyperkitty mailman3-full --purge`

**Comment by matebitte** [comment]
well, same problem here. context and steps to reproduce fit my scenario as well
